name: Build kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install nightly toolchain
      run: rustup toolchain install nightly
    - name: Install bootimage
      run: cargo install bootimage
    - name: Add target
      run: cd LUM && rustup target add x86_64-unknown-none
    - name: Build LUM
      run: cd LUM && cargo bootimage

