name: Build kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run rustup command
      run: rustup toolchain install nightly && rustup default nightly && cd LUM && rustup target add x86_64-unknown-none
    - name: Install bootimage
      run: cargo install bootimage
    - name: Build LUM
      run: cd LUM && cargo bootimage

