name: Build and push latest kernel compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install rust nightly, default it, add target, add src to nightly unknown and install llvm-tools-preview in rustup
      run: | 
        rustup toolchain install nightly
        rustup default nightly 
        cd LUM
        rustup target add x86_64-unknown-none
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu 
        rustup component add llvm-tools-preview 
    - name: Install bootimage
      run: cargo install bootimage
    - name: Build LUM
      run: cd LUM && cargo bootimage
    - name: Upload compiled kernel
      uses: actions/upload-artifact@v4
      with:
        name: bootimage-LUM.bin
        path: LUM/target/x86_64-unknown-none/debug/bootimage-LUM.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Boot Image
      uses: actions/download-artifact@v4
      with:
        name: bootimage
        path: ./release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/bootimage-LUM.bin
      env:
        GITHUB_TOKEN: ${{ secrets.LUMMARINERPUSH }}
      id: create_release
    - name: Tag the Release as Latest
      run: |
        git tag -f latest ${{ steps.create_release.outputs.upload_url }}
        git push origin -f latest

