name: Build kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install rust nightly, default it, add target, and add src to nightly unknown in rustup
      run: rustup toolchain install nightly && rustup default nightly && cd LUM && rustup target add x86_64-unknown-none && rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Install bootimage
      run: cargo install bootimage
    - name: Build LUM
      run: cd LUM && cargo bootimage

